version: "3.7"

services:
  dashboard_contract:
    image: kampn/php:8.0-fpm-search-dev-bullseye
    container_name: dashboard-contract-php
    networks:
      - internal
    user: runner
    volumes:
      - .:/srv
      - php_home:/home/runner

networks:
  internal: ~

volumes:
  php_home: ~
